'use client';

import { useState, useEffect } from 'react';
import { Columns, ArrowLeft, Key, Copy } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useMappingSuggestions } from '@/hooks/useMappingSuggestions';
import { getApiErrorMessage } from '@/lib/apiErrors';
import MappingRow from './MappingRow';
import TemplateSelector from './TemplateSelector';
import type {
  TableSchema,
  ColumnMapping,
  LookupRule,
  MappingSuggestion,
  TransformationType,
  StringToBooleanConfig,
  PrimaryKeyGenerationStrategy,
} from '@/types';

interface ColumnMapperProps {
  fileId: string;
  connectionString: string;
  tableName: string;
  excelColumns: string[];
  tableSchema: TableSchema;
  initialMappings?: ColumnMapping[];
  initialLookupRules?: LookupRule[];
  initialPrimaryKeyStrategy?: PrimaryKeyGenerationStrategy;
  initialDuplicateKeyColumns?: string[];
  onComplete: (
    mappings: ColumnMapping[],
    lookupRules: LookupRule[],
    primaryKeyGenerationStrategy?: PrimaryKeyGenerationStrategy,
    duplicateKeyColumns?: string[]
  ) => void;
  onBack: () => void;
}

function toMappingsRecord(mappings: ColumnMapping[]): Record<string, string> {
  const record: Record<string, string> = {};
  mappings.forEach((m) => {
    if (m.databaseColumn && !m.autoGenerate) record[m.excelColumn] = m.databaseColumn;
  });
  return record;
}

function toAutoGeneratedSet(mappings: ColumnMapping[]): Set<string> {
  const set = new Set<string>();
  mappings.forEach((m) => {
    if (m.autoGenerate && m.databaseColumn) set.add(m.databaseColumn);
  });
  return set;
}

function toTransformationDetails(
  mappings: ColumnMapping[]
): Record<string, { type: TransformationType; config?: StringToBooleanConfig }> {
  const details: Record<string, { type: TransformationType; config?: StringToBooleanConfig }> = {};
  mappings.forEach((m) => {
    if (m.transformationType && m.transformationType !== 'none' && m.transformationConfig) {
      details[m.excelColumn] = {
        type: m.transformationType,
        config: m.transformationConfig as StringToBooleanConfig,
      };
    }
  });
  return details;
}

export default function ColumnMapper({
  fileId,
  connectionString,
  tableName,
  excelColumns,
  tableSchema,
  initialMappings = [],
  initialLookupRules = [],
  initialPrimaryKeyStrategy = 'uuid',
  initialDuplicateKeyColumns = [],
  onComplete,
  onBack,
}: ColumnMapperProps) {
  const hasInitialState = initialMappings.length > 0;
  const [primaryKeyStrategy, setPrimaryKeyStrategy] =
    useState<PrimaryKeyGenerationStrategy>(initialPrimaryKeyStrategy);

  const [mappings, setMappings] = useState<Record<string, string>>(() =>
    hasInitialState ? toMappingsRecord(initialMappings) : {}
  );
  const [lookupRules, setLookupRules] = useState<LookupRule[]>(() =>
    hasInitialState ? initialLookupRules : []
  );
  const [duplicateKeyColumns, setDuplicateKeyColumns] = useState<Set<string>>(() =>
    new Set(initialDuplicateKeyColumns || [])
  );
  const [transformationDetails, setTransformationDetails] = useState<
    Record<string, { type: TransformationType; config?: StringToBooleanConfig }>
  >(() => (hasInitialState ? toTransformationDetails(initialMappings) : {}));
  const [autoGeneratedColumns, setAutoGeneratedColumns] = useState<Set<string>>(() =>
    hasInitialState ? toAutoGeneratedSet(initialMappings) : new Set()
  );

  const suggest = useMappingSuggestions();

  useEffect(() => {
    if (hasInitialState) return;
    suggest.mutate(
      { fileId, connectionString, tableName },
      {
        onSuccess: (suggestions: MappingSuggestion[]) => {
          const autoMap: Record<string, string> = {};
          suggestions.forEach((s) => {
            if (s.suggestedDbColumn && s.confidence >= 0.7) {
              autoMap[s.excelColumn] = s.suggestedDbColumn;
            }
          });
          setMappings(autoMap);

          const rules: LookupRule[] = [];
          for (const [excelCol, dbCol] of Object.entries(autoMap)) {
            const fk = tableSchema.foreignKeys.find((f) => f.columnName === dbCol);
            if (fk && fk.lookupDisplayColumn) {
              rules.push({
                foreignKeyColumn: dbCol,
                lookupTable: fk.referencedTable,
                lookupDisplayColumn: fk.lookupDisplayColumn,
                autoCreate: true,
                processingMode: 'lookup',
                foreignTableMappings: [],
              });
            }
          }
          setLookupRules(rules);
        },
      }
    );
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fileId, connectionString, tableName]);

  const handleMappingChange = (excelCol: string, dbCol: string) => {
    if (dbCol === '') {
      const prevDbCol = mappings[excelCol];
      setMappings((prev) => {
        const next = { ...prev };
        delete next[excelCol];
        return next;
      });
      if (prevDbCol) {
        setLookupRules((prev) => prev.filter((r) => r.foreignKeyColumn !== prevDbCol));
      }
      return;
    }

    setMappings((prev) => ({ ...prev, [excelCol]: dbCol }));

    const fk = tableSchema.foreignKeys.find((f) => f.columnName === dbCol);
    if (fk && fk.lookupDisplayColumn) {
      setLookupRules((prev) => {
        const existing = prev.find((r) => r.foreignKeyColumn === dbCol);
        if (existing) return prev;
        return [
          ...prev,
          {
            foreignKeyColumn: dbCol,
            lookupTable: fk.referencedTable,
            lookupDisplayColumn: fk.lookupDisplayColumn!,
            autoCreate: true,
            processingMode: 'lookup' as const,
            foreignTableMappings: [] as ColumnMapping[],
          },
        ];
      });
    }
  };

  const handleTransformationChange = (
    excelCol: string,
    type: TransformationType,
    config?: StringToBooleanConfig
  ) => {
    setTransformationDetails((prev) => {
      const next = { ...prev };
      if (type === 'none') {
        delete next[excelCol];
      } else {
        next[excelCol] = { type, config };
      }
      return next;
    });
  };

  const handleFkModeChange = (
    excelCol: string,
    dbCol: string,
    mode: 'lookup' | 'buildFromExcel' | 'useValueDirectly'
  ) => {
    setLookupRules((prev) =>
      prev.map((r) =>
        r.foreignKeyColumn === dbCol
          ? {
              ...r,
              processingMode: mode,
              foreignTableMappings: mode === 'buildFromExcel' ? r.foreignTableMappings || [] : [],
            }
          : r
      )
    );
  };

  const handleBuildMappingsChange = (dbCol: string, buildMappings: ColumnMapping[]) => {
    setLookupRules((prev) =>
      prev.map((r) =>
        r.foreignKeyColumn === dbCol ? { ...r, foreignTableMappings: buildMappings } : r
      )
    );
  };

  const handleBuildMatchColumnsChange = (dbCol: string, columns: string[]) => {
    setLookupRules((prev) =>
      prev.map((r) =>
        r.foreignKeyColumn === dbCol ? { ...r, buildMatchColumns: columns } : r
      )
    );
  };

  const handleApplyTemplate = (
    templateMappings: ColumnMapping[],
    templateRules: LookupRule[],
    templatePkStrategy?: PrimaryKeyGenerationStrategy,
    templateDuplicateKeyColumns?: string[]
  ) => {
    if (templatePkStrategy) setPrimaryKeyStrategy(templatePkStrategy);
    const map: Record<string, string> = {};
    const trans: Record<string, { type: TransformationType; config?: StringToBooleanConfig }> = {};
    const autoGen = new Set<string>();
    templateMappings.forEach((m) => {
      if (m.autoGenerate && m.databaseColumn) {
        autoGen.add(m.databaseColumn);
      } else if (excelColumns.includes(m.excelColumn)) {
        map[m.excelColumn] = m.databaseColumn;
        if (m.transformationType && m.transformationType !== 'none') {
          trans[m.excelColumn] = {
            type: m.transformationType,
            config: m.transformationConfig as StringToBooleanConfig,
          };
        }
      }
    });
    setMappings(map);
    setTransformationDetails(trans);
    setLookupRules(templateRules);
    setAutoGeneratedColumns(autoGen);
    setDuplicateKeyColumns(new Set(templateDuplicateKeyColumns || []));
  };

  const toggleAutoGenerate = (dbCol: string) => {
    setAutoGeneratedColumns((prev) => {
      const next = new Set(prev);
      if (next.has(dbCol)) {
        next.delete(dbCol);
      } else {
        next.add(dbCol);
        setMappings((m) => {
          const nextMap = { ...m };
          Object.keys(nextMap).forEach((excel) => {
            if (nextMap[excel] === dbCol) delete nextMap[excel];
          });
          return nextMap;
        });
      }
      return next;
    });
  };

  const handleContinue = () => {
    const columnMappings: ColumnMapping[] = [
      ...Array.from(autoGeneratedColumns).map((dbCol) => ({
        excelColumn: '',
        databaseColumn: dbCol,
        autoGenerate: true,
      })),
      ...Object.entries(mappings)
        .filter(([, db]) => db !== '')
        .map(([excel, db]) => {
          const detail = transformationDetails[excel];
          const mapping: ColumnMapping = { excelColumn: excel, databaseColumn: db };
          if (detail && detail.type !== 'none') {
            mapping.transformationType = detail.type;
            if (detail.config) mapping.transformationConfig = detail.config;
          }
          return mapping;
        }),
    ];
    onComplete(columnMappings, lookupRules, primaryKeyStrategy, Array.from(duplicateKeyColumns));
  };

  const toggleDuplicateKeyColumn = (dbCol: string) => {
    setDuplicateKeyColumns((prev) => {
      const next = new Set(prev);
      if (next.has(dbCol)) next.delete(dbCol);
      else next.add(dbCol);
      return next;
    });
  };

  const dbColumns = tableSchema.columns.map((c) => c.name);
  const usedDbColumns = new Set([...Object.values(mappings), ...autoGeneratedColumns]);
  const activeMappingCount = Object.values(mappings).filter(Boolean).length + autoGeneratedColumns.size;

  const mappedFromExcel = new Set(Object.values(mappings));
  const autoGenCandidates = tableSchema.columns.filter(
    (c) =>
      (tableSchema.primaryKeys.includes(c.name) || c.hasDefaultValue) &&
      !mappedFromExcel.has(c.name)
  );
  const duplicateKeyCandidates = Object.values(mappings).filter(
    (dbCol) => dbCol && !autoGeneratedColumns.has(dbCol)
  ) as string[];

  return (
    <Card>
      <CardHeader>
        <div className="flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2">
              <Columns className="w-5 h-5" />
              Column Mapping
            </CardTitle>
            <TemplateSelector
              tableName={tableName}
              onApply={handleApplyTemplate}
            />
          </div>
          <div className="flex items-center gap-4">
            <label className="text-sm font-medium">Primary key generation</label>
            <select
              value={primaryKeyStrategy}
              onChange={(e) =>
                setPrimaryKeyStrategy(e.target.value as PrimaryKeyGenerationStrategy)
              }
              className="h-8 rounded-md border border-input bg-background px-3 py-1 text-sm"
            >
              <option value="uuid">UUID (default)</option>
              <option value="databaseDefault">Database default</option>
            </select>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {suggest.isPending && (
          <div className="flex items-center gap-2 text-muted-foreground">
            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-primary" />
            Auto-matching columns...
          </div>
        )}

        {suggest.isError && (
          <div className="bg-destructive/10 text-destructive p-3 rounded-lg text-sm">
            Could not load mapping suggestions: {getApiErrorMessage(suggest.error)}
          </div>
        )}

        {duplicateKeyCandidates.length > 0 && (
          <div className="space-y-2 rounded-lg border border-muted p-4">
            <p className="text-sm font-medium flex items-center gap-2">
              <Copy className="w-4 h-4" />
              Duplicate detection (uniqueness key)
            </p>
            <p className="text-xs text-muted-foreground">
              Rows with duplicate values in these columns will be skipped. First occurrence wins.
            </p>
            <div className="flex flex-wrap gap-3 pt-2">
              {duplicateKeyCandidates.map((col) => (
                <label
                  key={col}
                  className="flex items-center gap-2 text-sm cursor-pointer"
                >
                  <input
                    type="checkbox"
                    checked={duplicateKeyColumns.has(col)}
                    onChange={() => toggleDuplicateKeyColumn(col)}
                    className="rounded border-input"
                  />
                  <span className="font-medium">{col}</span>
                </label>
              ))}
            </div>
          </div>
        )}

        {autoGenCandidates.length > 0 && (
          <div className="space-y-2 rounded-lg border border-muted p-4">
            <p className="text-sm font-medium flex items-center gap-2">
              <Key className="w-4 h-4" />
              Auto-generated columns (follows PK strategy)
            </p>
            <p className="text-xs text-muted-foreground">
              Columns below will be generated per row. Strategy: {primaryKeyStrategy === 'uuid' ? 'UUID' : 'Database default'}
            </p>
            <div className="flex flex-wrap gap-3 pt-2">
              {autoGenCandidates.map((col) => (
                <label
                  key={col.name}
                  className="flex items-center gap-2 text-sm cursor-pointer"
                >
                  <input
                    type="checkbox"
                    checked={autoGeneratedColumns.has(col.name)}
                    onChange={() => toggleAutoGenerate(col.name)}
                    className="rounded border-input"
                  />
                  <span className="font-medium">{col.name}</span>
                  {tableSchema.primaryKeys.includes(col.name) && (
                    <span className="text-xs text-muted-foreground">(PK)</span>
                  )}
                </label>
              ))}
            </div>
          </div>
        )}

        <div className="space-y-2">
          {excelColumns.map((excelCol) => {
            const suggestion = suggest.data?.find((s) => s.excelColumn === excelCol);
            const selectedDb = mappings[excelCol] || '';
            const lookupRule = lookupRules.find((r) => r.foreignKeyColumn === selectedDb);
            const transDetail = transformationDetails[excelCol];
            return (
              <MappingRow
                key={excelCol}
                excelColumn={excelCol}
                selectedDbColumn={selectedDb}
                dbColumns={dbColumns}
                usedDbColumns={usedDbColumns}
                confidence={suggestion?.confidence}
                tableSchema={tableSchema}
                excelColumns={excelColumns}
                connectionString={connectionString}
                transformationType={transDetail?.type}
                transformationConfig={transDetail?.config}
                lookupRule={lookupRule}
                onChange={(dbCol) => handleMappingChange(excelCol, dbCol)}
                onTransformationChange={
                  selectedDb && !tableSchema.foreignKeys.some((f) => f.columnName === selectedDb)
                    ? (type, config) => handleTransformationChange(excelCol, type, config)
                    : undefined
                }
                onFkModeChange={
                  lookupRule ? (mode) => handleFkModeChange(excelCol, selectedDb, mode) : undefined
                }
                onBuildMappingsChange={
                  lookupRule ? (m) => handleBuildMappingsChange(selectedDb, m) : undefined
                }
                onBuildMatchColumnsChange={
                  lookupRule && selectedDb
                    ? (cols) => handleBuildMatchColumnsChange(selectedDb, cols)
                    : undefined
                }
              />
            );
          })}
        </div>

        <p className="text-sm text-muted-foreground">
          {activeMappingCount} of {excelColumns.length} columns mapped
        </p>

        <div className="flex justify-between">
          <Button variant="outline" onClick={onBack}>
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back
          </Button>
          <Button onClick={handleContinue} disabled={activeMappingCount === 0}>
            Preview Data
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
